### ISSUE TITLE
Language Support 

### ISSUE THREAD

**Issue by harshadporwal** [springernature/snics-management#149]

**Comment by karentom** [comment]
@harshadporwal @mirellasprenger Are there still changes that need to be made for this ticket in the management portal?

**Comment by harshadporwal** [comment]
@mirellasprenger As we are good with Language support, this ticket can be closed right?

**Comment by mirellasprenger** [comment]
Language support completed and live with German, English, Portuguese and Spanish.
[RE_ Language support - Live.pdf](https://github.com/springernature/snics-management/files/3042093/RE_.Language.support.-.Live.pdf)
