### ISSUE TITLE
Filter fields in RCO Role are not getting cleared

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#241]
It seems the filter fields are not being cleared properly. When filtering on one field for an RCO, then doing a different filter by deleting the first and entering a new one, it does not clear the value in the first filtered field.

Example - Follow the following steps.

1. I filtered on 'Steph' in the name field.
![image](https://user-images.githubusercontent.com/17595871/54147632-f7d6fe00-4408-11e9-956f-f9ea71d2faad.png)

2. I started a new filter by deleting 'Steph' in the name field and entering 'karen' in the email field. (Image below shows only edits made to the fields. I did not hit enter to search yet.)
![image](https://user-images.githubusercontent.com/17595871/54148012-cad71b00-4409-11e9-8e0c-a166a8ad97ef.png)

3. I hit enter to filter for 'karen' in the email field and 'Steph' automatically appears in the name field again. No results are found because it is filtering on both.
![image](https://user-images.githubusercontent.com/17595871/54148132-112c7a00-440a-11e9-91e6-0918a6854747.png)

**Comment by harshadporwal** [comment]
@karentom The table filter function is working on 'Enter' hit. Even if you are clearing the filter you need to hit enter and then move on to next filtering. If you want I can change the functionality from 'Enter' hit to each character search while user is typing. But there was a issue faced last time i.e. it was change to 'Enter' hit.

**Comment by karentom** [comment]
I will check with Steph which solution she would prefer:
1. Hit 'Enter' after each filter change
or
2. Filter search after each character is entered (no Enter needed)

**Comment by karentom** [comment]
@harshadporwal Steph is fine with option #2. Can you please make the fix?

**Comment by karentom** [comment]
fixed
