### ISSUE TITLE
Admin role for modifying classification/questionnaires and for assigning role

### ISSUE THREAD

**Issue by harshadporwal** [springernature/snics-management#28]

**Comment by karentom** [comment]
I will check with Steph the requirements for this request.

**Comment by karentom** [comment]
@harshadporwal Can we disable the Questionnaires and RCO Role boxes for people who don't have the admin role?

![image](https://user-images.githubusercontent.com/17595871/54711557-94dc1a00-4b20-11e9-8b58-1b0220ef5535.png)

**Comment by karentom** [comment]
@harshadporwal Is it possible to give certain RCOs read-only access?

**Comment by harshadporwal** [comment]
@karentom What does read-only access mean?

**Comment by karentom** [comment]
Clarified 03/28/2019

**Comment by harshadporwal** [comment]
@karentom Admin role and read-only display functionality is available in UAT for testing.

**Comment by karentom** [comment]
@harshadporwal admin role is working, but not the read-only display. I'm closing this and keeping the read-only issue open.
