### ISSUE TITLE
Report duplicates

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#283]
Regarding the Excel download - the issue of the report showing the duplicates is still there .

I think the best way to handle these duplicates is to update the SNICS partner id to match. Most, if not all, of these are duplicated because they were migrated and then instead of renewing the assessment a new one was created for a new partner. The migrated SNICS partner id should be updated with the one that was created newly in SNICS. The external partner id should remain the same.

**Comment by karentom** [comment]
[SNICS DUPLICATE REPORTING TEST 2_Assessment-Report-2019-03-19-04-09-52-pm.csv.csv.xlsx](https://github.com/springernature/snics-management/files/2985342/SNICS.DUPLICATE.REPORTING.TEST.2_Assessment-Report-2019-03-19-04-09-52-pm.csv.csv.xlsx)

**Comment by harshadporwal** [comment]
@karentom We have created an endpoint to migrate the records. From the excel I got the records which needs to be migrated but I need to know from highlighted rows which partnerid needs to be updated

![image](https://user-images.githubusercontent.com/43807299/54682024-cf9b7d80-4b33-11e9-9d00-c0554eb07733.png)

Like in the above screenshot. How should it work,

3003595571 -> 3003595556
OR
3003595556 -> 3003595571

Please let me know if you didn't get my question.

**Comment by karentom** [comment]
@harshadporwal I had sent Steph an email asking her to confirm the changes. We'll wait on her to confirm before making changes.

**Comment by karentom** [comment]
@harshadporwal Here is the latest file with duplicates and merges.

[Copy of SNICS.DUPLICATES_V3.xlsx](https://github.com/springernature/snics-management/files/3003509/Copy.of.SNICS.DUPLICATES_V3.xlsx)

**Comment by harshadporwal** [comment]
@karentom All merges and deletion are done

**Comment by karentom** [comment]
@harshadporwal 

There seems to be an issue with the changes. I checked the first 3 that have been merged and it seems that all statuses have been changed to Contract Only. Since all the merged ones are migrated partners, there should be at least one assessment that is 'Expired'.

![image](https://user-images.githubusercontent.com/17595871/55101144-d7aa6e80-5099-11e9-85c7-09946d8cb6a4.png)

**Comment by harshadporwal** [comment]
@karentom The original status has been reverted back. There is program running in background which upated its status to Contract only. The fix is in place. Please check.

**Comment by karentom** [comment]
@harshadporwal looks good
