### ISSUE TITLE
Change text of “Reassign Employee” button to “Reassign Owner”

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#288]
![image](https://user-images.githubusercontent.com/17595871/54711677-d240a780-4b20-11e9-821e-9d17c498e28f.png)

**Comment by harshadporwal** [comment]
Fixed and working in UAT

![image](https://user-images.githubusercontent.com/43807299/54821774-343c1100-4cc9-11e9-828d-25d66a7ca4be.png)

**Comment by karentom** [comment]
@harshadporwal looks good. thanks.
