### ISSUE TITLE
Add ‘Links’ as the heading in the last column in the Business Partner Overview

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#289]
![image](https://user-images.githubusercontent.com/17595871/54711882-4aa76880-4b21-11e9-957c-56e4f821a04c.png)

**Comment by harshadporwal** [comment]
Fixed and working in UAT

![image](https://user-images.githubusercontent.com/43807299/54821837-68173680-4cc9-11e9-8464-54c56f7de26f.png)

**Comment by karentom** [comment]
@harshadporwal looks good. thanks.
