### ISSUE TITLE
Questionnaire filter should be a dropdown 

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#290]
The Questionnaire filter doesn't work, but it should be changed to a drop down anyway.

![image](https://user-images.githubusercontent.com/17595871/54711973-84786f00-4b21-11e9-8570-227cc6b0e06d.png)

**Comment by harshadporwal** [comment]
Fixed and working in UAT

![image](https://user-images.githubusercontent.com/43807299/54821920-96951180-4cc9-11e9-9b0f-601f8fbaaef6.png)

**Comment by karentom** [comment]
@harshadporwal looks good. thanks
