### ISSUE TITLE
RCO role that is display only and do not receive emails

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#301]
There are RCOs that should not have the ability to modify anything in the management portal. These RCOs should also not receive any emails that are normally sent out to RCOs.

**Comment by harshadporwal** [comment]
@karentom Need more clarification on this requirment. What does 'Display only' mean?

**Comment by karentom** [comment]
Clarified 03/28/2019

**Comment by harshadporwal** [comment]
@karentom The admin role and read_only display functionality is completed. Should move the code to UAT for testing?

**Comment by karentom** [comment]
@harshadporwal I was able to still make edits when the read-only checkbox was marked for me.

**Comment by harshadporwal** [comment]
@karentom Once the read-only access is assigned, the user who is assigned needs to logout and login again. Then only it will work.

**Comment by harshadporwal** [comment]
@karentom Hidden the contacts button, upload button and reassign button for read_only display.

**Comment by karentom** [comment]
@harshadporwal Looks good. Closing issue.
