### ISSUE TITLE
Notes are missing from reviewed answers

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#322]
![image](https://user-images.githubusercontent.com/17595871/55251202-5b916180-5226-11e9-8fb8-05595126a64d.png)

A note was added to this answer that has been reviewed, but no note is displayed. We found 2 examples of this and both were reviewed from the old system. We checked one that was reviewed in the new system and the note was found. Can you check if the notes have been migrated over to the new system? If it has, then please look at why the notes are missing from the 2 examples - partner id 747 and 804.

**Comment by harshadporwal** [comment]
@karentom All the data was migrated from old system. And I have checked the data, the note field is empty so the notes are missing. I have teste this functionality in UAT and its working fine.

**Comment by karentom** [comment]
Explained this issue to Steph. It's a symptom of the old system.  Data was migrated this way.
