### ISSUE TITLE
Downloadable Report from Pie Chart

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#348]
When you click into a slice of the pie chart, it takes you to a new page that lists all records within it. Can we add a button to download that data into an Excel file?

For example:
When you click into 'Level 2' of the 'Labour standards risk' pie chart, it takes you to the list of all records for Level 2.
![image](https://user-images.githubusercontent.com/17595871/55899305-72bf4000-5b92-11e9-976f-8648b971ac7f.png)

Can we add 'Full statistics' and 'Download report' buttons to that page which will then create an Excel file with all records for that selection?

![image](https://user-images.githubusercontent.com/17595871/55899735-84edae00-5b93-11e9-8c3e-0571844bd4cb.png)

**Comment by harshadporwal** [comment]
@karentom Added download report functionality for the pie chart. Also if the country filter is applied, the report will also be downlaoded based on filtered country.

**Comment by karentom** [comment]
@harshadporwal Tested and looks great. Closing this issue.
