### ISSUE TITLE
Time Zone date issue - discrepancy between assessments and documents

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#351]
There seems to be the time zone issue with the documents section. In the example below, I had uploaded 2 contracts and both dates are displaying incorrectly. They are displaying a day behind because of the time zone issue. The dates should be July 9, 2019 and July 10, 2019. 

![image](https://user-images.githubusercontent.com/17595871/55907556-17e31400-5ba5-11e9-9dcc-b8bb45378778.png)

**Comment by harshadporwal** [comment]
@karentom Fixed zone issue. Please test it and let me know if issue still exist

**Comment by karentom** [comment]
@harshadporwal Looks good. Thanks.
