### ISSUE TITLE
Delete Patner functionality

### ISSUE THREAD

**Issue by harshadporwal** [springernature/snics-management#374]

**Comment by harshadporwal** [comment]
https://github.com/springernature/snics-employee/issues/297

**Comment by harshadporwal** [comment]
@karentom @mirellasprenger  Added delete partner functionality and will be accessble only for admin role. 'Delete Partner' button is available in partner details page. Please test it in UAT and let me know if any issues.

**Comment by karentom** [comment]
@harshadporwal The delete partner works, but I need to check with Steph if this is sufficient or if we need it on the assessment level. Also want to confirm the text in the confirmation box.

**Comment by karentom** [comment]
@harshadporwal In the confirmation box, please add the text:

"Are you sure you want to delete the Partner? The Partner will be deleted from SNICS but the SAP record will still exist (if it has been created in SAP). Check with snics@springernature.com  to see if the Partner should also be deleted in SAP."

**Comment by harshadporwal** [comment]
@karentom Updated the text for confirmation box.

**Comment by karentom** [comment]
@harshadporwal I clicked on the "Cancel" button and it still deleted the partner.

**Comment by harshadporwal** [comment]
@karentom Cancel button issue is fixed.

**Comment by karentom** [comment]
@harshadporwal Tested. Looks good.
