### ISSUE TITLE
Set Review Date is not updating the review date

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#91]
The review date is not changing in the management dashboard after it was changed through the 'Set Review Date' button.

![image](https://user-images.githubusercontent.com/17595871/51333199-3d033300-1a4b-11e9-8f5b-eb6d3eb94d73.png)

Review date does not change on management dashboard.
![image](https://user-images.githubusercontent.com/17595871/51333298-6e7bfe80-1a4b-11e9-92c2-f66423d0620e.png)

**Comment by karentom** [comment]
@harshadporwal When I change the review date, it saves it as the day before. 

![image](https://user-images.githubusercontent.com/17595871/54575536-c773fe80-49ca-11e9-8b76-f525bbb7b7d7.png)

![image](https://user-images.githubusercontent.com/17595871/54575562-e5d9fa00-49ca-11e9-876c-a33565d05dd7.png)

**Comment by harshadporwal** [comment]
@karentom I have tested it and it looks fine. I didn't fidnany issues.

![image](https://user-images.githubusercontent.com/43807299/54597536-bbd11800-4a5c-11e9-86cc-8a52a97185c4.png)

![image](https://user-images.githubusercontent.com/43807299/54597564-c55a8000-4a5c-11e9-998a-8b9c3f759384.png)

**Comment by karentom** [comment]
@harshadporwal I believe it has something to do with the time zones. Could it be one the front end is one time zone and the back end another? I cannot think of another reason why this would happen.

**Comment by harshadporwal** [comment]
@karentom I have added the UTC time now. Can you please test now and let me know if the issue still exist.

**Comment by karentom** [comment]
@harshadporwal The issue is still there.

**Comment by harshadporwal** [comment]
@karentom Can you please test now? Added some fix

**Comment by karentom** [comment]
@harshadporwal The issue is still there.

**Comment by harshadporwal** [comment]
@karentom It is fixed now. I have changed my laptops timezone and tested. Please check now.

**Comment by karentom** [comment]
@harshadporwal Yes! It works!

**Comment by karentom** [comment]
@harshadporwal The issue is now appearing in the box where you set the date. I had selected 4/27/2019 but it's saved in the box as 4/26/2019. The assessment is displaying the correct date.

![image](https://user-images.githubusercontent.com/17595871/55183395-1279d880-5166-11e9-851d-8b55c7e523b6.png)

![image](https://user-images.githubusercontent.com/17595871/55183415-232a4e80-5166-11e9-9919-63a7b68990e2.png)

**Comment by harshadporwal** [comment]
@karentom Fixed review date for dialog.

**Comment by karentom** [comment]
@harshadporwal thanks. looks good.
